### ISSUE TITLE
Does not work with XBee

### ISSUE THREAD

**Issue by leighandrewtm** [MrYsLab/rbDashBoard#2]
Tried running the rbDashBoard program using XBees. The connection to the Arduino is successful, but the website does not automatically pop up like it does when you connect via USB.  

When attempting to manually connect by opening the web page myself I get this error log:

```
    Client connecting: tcp:127.0.0.1:52587
    WebSocket connection open.
    Exception in callback WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at C:\Python34\lib\site-packages\autobahn\asyncio\websocket.py:102
    handle: <Handle WebSocketAdapterProtocol._consume.<locals>.process(<Future finished result=None>) at C:\Python34\lib\site-packages\autobahn\asyncio\websocket.py:102>
    Traceback (most recent call last):
      File "C:\Python34\lib\asyncio\events.py", line 120, in _run
        self._callback(*self._args)
      File "C:\Python34\lib\site-packages\autobahn\asyncio\websocket.py", line 106, in process
        self._dataReceived(data)
      File "C:\Python34\lib\site-packages\autobahn\websocket\protocol.py", line 1313, in _dataReceived
        self.consumeData()
      File "C:\Python34\lib\site-packages\autobahn\websocket\protocol.py", line 1345, in consumeData
        self.processHandshake()
      File "C:\Python34\lib\site-packages\autobahn\websocket\protocol.py", line 3082, in processHandshake
        self._onConnect(request)
      File "C:\Python34\lib\site-packages\autobahn\asyncio\websocket.py", line 200, in _onConnect
        self.succeedHandshake(res)
      File "C:\Python34\lib\site-packages\autobahn\websocket\protocol.py", line 3305, in succeedHandshake
        self._onOpen()
      File "C:\Python34\lib\site-packages\autobahn\asyncio\websocket.py", line 123, in _onOpen
        res = self.onOpen()
      File "C:/Users/mathewla/Documents/GitHub/rbDashBoard/dashboard/redbot.py", line 43, in onOpen
        self.rb_control.establish_socket(self)
    AttributeError: 'NoneType' object has no attribute 'establish_socket'
```

Any suggestions for getting XBees to work?

**Comment by MrYsLab** [comment]
I found a race condition an the repair partially fixes the issue. I have pushed the files to github and enabled console logging to view messages coming to the web page. Wired seems to work as expected. With XBee the web page still needs to be loaded manually (sometimes). So if you load the web page, start the server and then reload the web page, you should no longer see the exception. Motor control works and so does the IR sensor reporting. For some reason, the accelorometer seems to not be available with XBee. I will need to investigate this further.

**Comment by MrYsLab** [comment]
I spent the day trying to trouble shoot using all sensors with XBee. In a wired configuration, all works, but if XBee is used the accelerometer never reports that it is available for a data read. I tried programming the XBees at various baudrates from 19,200 to 115200 and that did not change the behavior. (115200 did not communicate at all with my script - but does for wired configuration). I tried changing the Firmata loop times from 10 ms up to 400 ms and again, no change. I tried putting breakpoints at strategic places to allow the i2c device time to react, and again no change.

It appears that having  input sensors that report rapid changes (the IR sensors and the encoders) in conjunction with the XBees stops the accelerometer from functioning.

I don't know if  the rapid pin value changes in conjunction with the XBee is causing some type of gitter that hangs the i2c device or not (I don't own an oscilloscope, so this is a guess).

So the solution (or workaround) will be, that if using XBEEs, accelerometer data will be unavailable.

I am closing this issue at the moment, since I cannot prove that is a software issue.
